config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'homepages#index'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/concerts' => 'concerts#index'
  get '/concerts/new' => 'concerts#new'
  post '/concerts' => 'concerts#create'
  get '/concerts/:id' => 'concerts#show'
  get '/concerts/:id/edit' => 'concerts#edit'
  patch '/concerts/:id' => 'concerts#update'
  delete '/concerts/:id' => 'concerts#destroy' 


  

  get '/venues' => 'venues#index'
  get '/venues/new' => 'venues#new'
  post '/venues' => 'venues#create'
  get '/venues/:id' => 'venues#show'
  get '/venues/:id/edit' => 'venues#edit'
  patch '/venues/:id' => 'venues#update'
  delete '/venues/:id' => 'venues#destroy' 

  get '/reviews' => 'reviews#index'
  get '/reviews/new' => 'reviews#new'
  post '/reviews' => 'reviews#create'
  get '/reviews/:id' => 'reviews#show'
  get '/reviews/:id/edit' => 'reviews#edit'
  patch '/reviews/:id' => 'reviews#update'
  delete '/reviews/:id' => 'reviews#destroy' 

  get '/tickets' => 'tickets#index'
  get '/tickets/new' => 'tickets#new'
  post '/tickets' => 'tickets#create'
  get '/tickets/:id' => 'tickets#show'
  get '/tickets/:id/edit' => 'tickets#edit'
  patch '/tickets/:id' => 'tickets#update'
  delete '/tickets/:id' => 'tickets#destroy'

  post '/user_concerts' => 'user_concerts#create'

  post '/google_calendars' => 'google_calendars#create'

  get '/notifications' => 'notifications#sendmessage'

  namespace :api do
    namespace :v1 do
      get '/concerts' => 'concerts#index'
      get 'user_concerts' => 'user_concerts#index'
      post 'reviews' => 'reviews#create'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_concerts
  has_many :concerts, through: :band_concerts
end

app/models/band_concert.rb
class BandConcert < ApplicationRecord
  belongs_to :band
  belongs_to :concert
end

app/models/concert.rb
class Concert < ApplicationRecord

  has_many :tickets
  belongs_to :venue
  belongs_to :calendar
  has_many :user_concerts
  has_many :users, through: :user_concerts
  has_many :band_concerts
  has_many :bands, through: :band_concerts


  def friendly_date
    friendly_date = date.strftime("%A, %b %d")
  end

  def date_and_headliner
    return bands.first.name + ' ' + date.strftime("%A, %b %d") + " at " + Venue.find_by(id: venue_id).name
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :users
  belongs_to :venue
end

app/models/ticket.rb
require 'twilio-ruby'
class Ticket < ApplicationRecord
  belongs_to :seller, class_name: :User, foreign_key: :seller_id
  belongs_to :buyer, class_name: :User, foreign_key: :buyer_id
  belongs_to :concert

  def toggle_ticket_fullfillment 
    if ticket_fulfilled == true
      ticket_fulfilled = false
    else
      ticket_fulfilled = true
    end
  end

  def friendly_payment_status
    if seller_paid == true
      return 'Payment Recieved'
    else
      return 'Awaiting Payment'
    end
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews
  has_many :bought_tickets, class_name: :Ticket, foreign_key: :buyer_id
  has_many :sold_tickets, class_name: :Ticket, foreign_key: :seller_id
  has_many :user_concerts
  has_many :concerts, through: :user_concerts
end

app/models/user_concert.rb
class UserConcert < ApplicationRecord
  belongs_to :user 
  belongs_to :concert 
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :concerts
  has_many :reviews
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render 'new.html.erb'
  end

  def create
    user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      profile_pic: 'prof8.jpg',
      phone_number: params[:phone_number],
      password_confirmation: params[:password_confirmation]
    )
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Successfully created account!'
      redirect_to '/'
    else
      flash[:warning] = 'Invalid email or password!'
      redirect_to '/signup'
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.all
    render 'index.html.erb'
  end

  def new
    render 'new.html.erb'
  end

  def create
    @venue = Venue.new(
      name: params[:rating],
      description: params[:description],
      user_id: current_user.id
      )
    @venue.save

  end

  def show
    @venue = Venue.find_by(id: params[:id])
    @concerts = Concert.where(venue_id: @venue.id).order('date')
  end

  def edit
    @venue = Venue.find_by(id: params[:id])
    render 'edit.html.erb'
  end

  def update
    @venue = venue.find_by(id: params[:id])
    @venue.rating = params[:rating]
    @venue.description = params[:description]
    #maybe add @venue.user_id = current_user/session.id
    @venue.save
  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/briefcases_helper.rb
module BriefcasesHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_bands_helper.rb
module UserBandsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-sm-12">

            
          
        </div>
      </div> <!-- / .row -->
      
      <div class="row isotope-container">
      <% @venues.each do |venue| %>
        <div class="col-sm-4 col-lg-3 isotope-item category_1">
          
          <a href="/venues/<%= venue.id%>" class="thumbnail alt">
            <img src="assets/img/<%= venue.image %>" alt="...">
            <div class="caption">
              <h5><%=venue.name %> </h5>
            <% if venue.reviews.first %>
              <ul class="rating">
              <% venue.reviews.first.rating.times do %>
                <li><i class="fa fa-star"></i></li>
                <% end %>
              </ul>
            <% end %>
              <p>
                Will call exchange policy: <%= venue.will_call_policy %>
              </p>
            </div>
          </a>

        </div>
        <% end %>
      </div> <!-- / .row -->
    </div> <!-- / .container -->

app/views/venues/new.html.erb
<h1>Add a concert</h1>

<%= form_tag '/venue', method: :post do %>
  <div class="form-group">
  <%= label_tag :name, 'Enter a venue name: ' %>
  <%= text_field_tag :name, '', class: 'form-control' %>
  </div>
   <div class="form-group">
  <%= label_tag :doors, 'Enter doors time' %>
  <%= text_field_tag :doors, @concert.doors, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= label_tag :show, 'Enter show time: ' %>
  <%= text_field_tag :show, @concert.show, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= label_tag :date, 'Enter concert date: ' %>
  <%= text_field_tag :date, @concert.date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :band_ids, "Select a band:" %>
    <%= collection_select(:band_ids, :first_band, Band.all, :id, :name) %>
  </div>
  <div class="form-group">
    <%= label_tag :band_ids, "Select another band:" %>
    <%= collection_select(:band_ids, :second_band, Band.all, :id, :name) %>
  </div>
  <div class="form-group">
    <%= label_tag :band_ids, "Select another band:" %>
    <%= collection_select(:band_ids, :third_band, Band.all, :id, :name) %>
  </div>


  <div class="form-group">
  <%= label_tag :band2, 'Enter concert band: ' %>
  <%= text_field_tag :band2, '', class: 'form-control' %>
  </div> 
  <div class="form-group">
  <%= label_tag :band3, 'Enter concert band: ' %>
  <%= text_field_tag :band3, '', class: 'form-control' %>
  </div>
  <div>
  <%= submit_tag 'Submit product!' %>
  </div>
<% end %>

app/views/venues/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7">
      <!-- Main image -->
      <a href="/" data-lightbox="...">
        <img src="../assets/img/<%= @venue.image %>" alt="..." class="img-responsive">
      </a>
      <% if current_user %>
        <h1 class="block-header alt">
          <span>Reviews</span>
        </h1>
        <%= form_tag '/reviews', method: :post do %>

        <div class="form-group">
          <%= hidden_field_tag :venue_id, @venue.id %>
        </div>
        <div class="form-group">
        <%= label_tag :rating, 'Enter a rating: ' %>
        <%= select_tag :rating, options_for_select(1..5), multipe: false, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag :description, 'Enter  a description' %>
          <%= text_field_tag :description, '', class: 'form-control' %>
        </div>
        <div>
          <%= submit_tag 'Submit review!' %>
        </div>
        <% end %>
      <% end %>
      <div class="comments">
        <div class="comments__heading">Reviews</div>
          <!-- List of comments -->
          <div class="comments__list">
            <!-- Comment item -->
            <% @venue.reviews.each do |review| %>
              <div class="comments__item">
                <div class="comments-item__avatar">
                  <img src="../assets/img/<%= User.find_by(id: review.user_id).profile_pic %>" class="img-responsive" alt="..." />
                </div>
                <div class="comments-item__body">
                  <div class="comments-item__info">
                    <div class="comments-item-info__author"><%= User.find_by(id: review.user_id).name %>
                    </div>
                    <div class="comments-item-info__divider">
                      <i class="fa fa-circle"></i>
                    </div>
                    <ul class="rating">
                      <% review.rating.times do %>
                        <i class="fa fa-star"></i>
                      <% end %>
                    </ul>
                  </div>
                  <div class="comments-item__content">
                    <%= review.description %>
                  </div>
                  <div class="comments-item__actions">
                    <a href="#" class="comment-item-actions__reply">
                      Reply
                    </a>
                  </div>
                </div>
              </div> <!-- / .comments__item -->
            <% end %>
          </div> <!-- / .comments__list -->
        </div> <!-- / .comments -->
      </div>
      <div class="col-sm-5">
        <h1 class="block-header alt">
          <span><%= @venue.name%></span>
        </h1>
        <p>Will call policy: <%=@venue.will_call_policy%></p>
        <h1 class="block-header alt">
          <span>Tickets</span>
        </h1>
        <a href="/tickets?venue=<%=@venue.id%>"><button>See Available</button></a>    
        <h1 class="block-header alt">
          <span>Upcoming shows</span>
        </h1>
        <div>
          <a href="/concerts?venue_id=<%=@venue.id%>"><button>See All</button></a>
        </div>
        <div class="row">
          <% if @concerts.first %>
            <% @concerts.each do |concert| %>
              <div class="col-sm-6">
                <a href="/concerts/<%= concert.id %>" class="thumbnail">
                  <% if concert.picture.include?('gig_buddies') %>
                    <img src="/<%= concert.picture %>" alt="...">
                  <% else %>
                    <img src="<%= concert.picture %>" alt="...">
                  <% end %>
                  <div class="caption hidden">
                    <h5>Project Title</h5>
                    <ul class="rating">
                      <li><i class="fa fa-star"></i></li>
                      <li><i class="fa fa-star"></i></li>
                      <li><i class="fa fa-star"></i></li>
                      <li><i class="fa fa-star"></i></li>
                      <li><i class="fa fa-star"></i></li>
                    </ul>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    </p>
                  </div>
                </a> 
              </div>
            <% end %>
          <% end %>
        </div> <!-- / .row -->
      </div>
      <iframe
      width="450"
      height="450"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=<%=ENV['GOOGLE_API_KEY']%>
        &q=<%= @venue.name%>,Chicago+IL" allowfullscreen>
      </iframe>
    </div> <!-- / .row -->
  </div> <!-- / .container -->